name: Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Kotlin compiler
        run: curl -L https://github.com/JetBrains/kotlin/releases/download/v1.5.0/kotlin-compiler-1.5.0.zip -o kotlinc.zip && unzip kotlinc.zip
      - name: Download JUnit Platform standalone JAR
        run: curl -L https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0.jar -o junit-platform-console-standalone-1.7.0.jar
      - name: Build with Kotlin compiler
        run: kotlinc/bin/kotlinc -cp junit-platform-console-standalone-1.7.0.jar -include-runtime -d output.jar src/main/kotlin/
      - name: Run tests
        run: kotlinc/bin/kotlinc -cp junit-platform-console-standalone-1.7.0.jar -script src/test/runTests.kts
